version: '3.1'

networks:
  backend:
    driver: {{ NETWORKS_DRIVER }}

volumes:
  mysql:
    driver: {{ VOLUMES_DRIVER }}

services:

  php-fpm:
    build: ./services/php-fpm
    container_name: {{ CONTAINER_PREFIX }}{{ CONTAINER_NAME }}-php-fpm
    volumes:
      - ./www:/var/www
      - ./services/php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
    networks:
      - backend

  nginx:
    build: ./services/nginx
    container_name: {{ CONTAINER_PREFIX }}{{ CONTAINER_NAME }}-nginx
    volumes:
      - ./www:/var/www
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '{{ NGINX_PORT }}:80'
    depends_on:
      - php-fpm
    networks:
      - backend

  mysql:
    build:
      context: ./services/mysql
      args:
        - MYSQL_VERSION={{ MYSQL_VERSION }}
        - TZ={{ MYSQL_TIMEZONE }}
    container_name: {{ CONTAINER_PREFIX }}{{ CONTAINER_NAME }}-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE={{ MYSQL_DATABASE }}
      - MYSQL_USER={{ MYSQL_USER }}
      - MYSQL_PASSWORD={{ MYSQL_PASSWORD }}
      - TZ={{ MYSQL_TIMEZONE }}
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - '{{ MYSQL_PORT }}:3306'
    depends_on:
      - nginx
    networks:
      - backend